<a href="https://colab.research.google.com/github/DikshaNadiga123/BIS-LAB/blob/main/ParallelCellular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

def noise_reduction(grid, iterations):
    """
    Reduces noise in a grid using averaging with neighbors.

    Parameters:
    grid (numpy.ndarray): 2D array representing the noisy grid.
    iterations (int): Number of iterations for noise reduction.

    Returns:
    numpy.ndarray: Grid after noise reduction.
    """
    rows, cols = grid.shape

    for _ in range(iterations):
        # Create a copy of the grid to apply updates
        new_grid = grid.copy()

        for i in range(1, rows - 1):
            for j in range(1, cols - 1):
                # Update each cell by averaging its value with neighbors
                neighbors = [
                    grid[i - 1][j], grid[i + 1][j], grid[i][j - 1], grid[i][j + 1],
                    grid[i - 1][j - 1], grid[i - 1][j + 1], grid[i + 1][j - 1], grid[i + 1][j + 1]
                ]
                new_grid[i][j] = int((grid[i][j] + sum(neighbors)) / (len(neighbors) + 1))

        grid = new_grid  # Update the grid for the next iteration

    return grid

def main():
    """
    Main function to demonstrate noise reduction on a grid.
    """
    # Take user input for grid dimensions and noise level
    rows = int(input("Enter number of rows for the grid: "))
    cols = int(input("Enter number of columns for the grid: "))
    iterations = int(input("Enter the number of iterations for noise reduction: "))

    # Generate a random noisy grid
    np.random.seed(0)  # For reproducibility
    grid = np.random.randint(0, 256, (rows, cols))

    print("\nOriginal Grid (Noisy Image):")
    print(grid)

    # Perform noise reduction
    reduced_grid = noise_reduction(grid, iterations)

    print("\nReduced Noise Grid (After Noise Reduction):")
    print(reduced_grid)
    print("\nOutput: Noise reduction completed successfully!")

if __name__ == "__main__":
    main()


Enter number of rows for the grid: 3
Enter number of columns for the grid: 3
Enter the number of iterations for noise reduction: 5

Original Grid (Noisy Image):
[[172  47 117]
 [192  67 251]
 [195 103   9]]

Reduced Noise Grid (After Noise Reduction):
[[172  47 117]
 [192 135 251]
 [195 103   9]]

Output: Noise reduction completed successfully!
